### ISSUE TITLE
Signs don't work in the overworld

### ISSUE THREAD

**Issue by Schwanzz** [DRE2N/DungeonsXL#406]
Hi,

I'm trying to place signs to teleport, create groups and join/leave groups.
I am following your format:

[DXL]
Vex
Ancienthills
6, Vex

But it does nothing. The signs are just signs with no effects.

What is the issue?

**Comment by Sataniel98** [comment]
My bad, just realized there is actually no way for a new user to get that the second line is supposed to be literally "Group" or "Game" in a global sign. That's NOT a placeholder. I'll fix that in the documentation :) Also, you should get rid of that space between "6," and "Vex".

BTW: Please consider updating to the new version that I just published.

**Comment by Schwanzz** [comment]
I still cannot click the signs in any way in the normal world.

I can however click the signs inside of the dungeon now.

How do I make the signs in the normal world clickable?

**Comment by Sataniel98** [comment]
You need the permission to create signs, or to be OP.

Syntax in 0.16:

[DXL]
Group
Ancienthills
6,Vex

Before 0.16:

[DXL]
Group
Ancienthills
1,6

I guess you might have grabbed the latest build from SpigotMC.org, but the latest build has a different syntax.

**Comment by Sataniel98** [comment]
Did you get it to work?

**Comment by Schwanzz** [comment]
Yes, it works now, thank you!

However, right now when I'm in the dungeon, ghasts and creepers can destroy the map.
Is there any way to turn the mob griefing off?
